### ISSUE TITLE
Yaml anchors not preserved

### ISSUE THREAD

**Issue by ext** [sapegin/mrm#180]
When using the builtin `yaml` helpers the anchors are not preserved.

## Steps to reproduce

Given a task such as:

```js
const { yaml } = require("mrm-core");

module.exports = function myFancyTask() {
    const file = yaml('my-file.yml');
    file.unset('my-key');
    file.save();
}

module.exports.description = "My awesome task";
```

and an input file (`my-file.yml`) using anchoes/aliaes simliar to this:

```yml
my-key: true

.base: &base
  foo: bar
  spam: ham

sub:
  <<: *base
```

## Actual results

After running the task the anchors are changed into this:

```yml
.base:
  foo: bar
  spam: &ref_0
    - 1
    - 2
    - 3
sub:
  foo: bar
  spam: *ref_0
```

## Expected results

```yml
.base: &base
  foo: bar
  spam: ham

sub:
  <<: *base
```
